def count_sentences_starting_with_b(text):
    sentences = text.split(".")
    count = 0
    for sentence in sentences:
        if sentence.strip().startswith("B"):
            count += 1
    return count

text = '''The apple doesn't fall. ...
All that glitters are not gold. ...
A picture is worth a thousand words. ...
Beggers can't be choosers. ...
A bird in the hand. ...
Better safe than sorry. ...
An apple a day keeps doctor away. ...
Blood is thicker than water. ...'''

result = count_sentences_starting_with_b(text)
print("Number of sentences starting with 'B':", result)
